stages:
  - mirror

push-mirror:
  stage: mirror
  script:
    - git remote rm github || true
    - git remote add github git@github.com:Teaspot-Studio/minetest-epsylon.git || true
    - git push github HEAD
