stages:
  - mirror

push-mirror:
  stage: mirror
  script:
    - git remote remove github || true
    - git remote add --mirror github git@github.com:Teaspot-Studio/minetest-epsylon.git || true
    - git push --mirror github
